# Generated by Django 4.0.3 on 2023-10-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EncoreAnswer',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='EncoreQuestion',
            new_name='Question',
        ),
    ]
