# Generated by Django 4.0.3 on 2023-10-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encore', '0002_rename_encoreanswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='create_time',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='create_time',
            new_name='create_date',
        ),
    ]
